- src/ngx_http_vhost_traffic_status_module.c
When a request fail and have an error_page configured for it the vts module will not have access to r->cache because a cache file isn't created.
The problem can be easily reproduced with any request to a nginx with the bellow configuration.
```
pid         logs/nginx.pid;
error_log   logs/nginx-main_error.log debug;
worker_processes    2;
events {
worker_connections  1024;
use                 epoll; # Linux
}
http {
default_type    text/plain;
vhost_traffic_status_zone;
types {
text/html   html;
}
log_format main  '[$time_local] $host "$request" $request_time s '
'$status $body_bytes_sent "$http_referer" "$http_user_agent" '
'cache_status: "$upstream_cache_status" args: "$args '
'sorted_args: "$sorted_querystring_args" ';
access_log       logs/nginx-http_access.log;
proxy_cache_path …
```
> Bugfix: stats for cached responses with error_page directive do not create a cache file

- README.md
Hi everyone,
I came here because my team had problems understanding how the averages (for example `responseMsec`) are being calculated. I skimmed over the issues and found #73, where I got a basic idea of this fixed queue and WMA. I think this information would be very valuable in the README. Please understand my PR as a starting point, there might be much more interesting calculation logic that is right now only documented implicitly in the code.
Regards,
Tobi
> Include general calculation logic in readme

- src/ngx_http_vhost_traffic_status_display.c
Patched issue: peer->down not always indicates correct server state.
Behavion with the patch same as ngx_upstream_status module provides: https://github.com/anomalizer/ngx_upstream_status
Upstream zone must be configured: http://nginx.org/ru/docs/http/ngx_http_upstream_module.html#zone
> Fixed upstream server state.

- src/ngx_http_vhost_traffic_status_display_prometheus.c
- src/ngx_http_vhost_traffic_status_display_prometheus.h
This improves the status metrics to conform more closely to Prometheus conventions.
* Use seconds rather than milliseconds for Prometheus metrics, this conforms with the best practice to expose base units[0].
* Separate version info metric from uptime.
- Allows for queries like `count(nginx_vts_info) by (version)`.
* Use absolute start time rather than uptime.
- Allows for queries like `changes(nginx_vts_start_time_seconds[1d])` or `time() - nginx_vts_start_time_seconds`.
[0]: https://prometheus.io/docs/practices/naming/#base-units
> Improve Prometheus metrics

- src/ngx_http_vhost_traffic_status_display_json.c
There is a small typo in src/ngx_http_vhost_traffic_status_display_json.c.
Should read `destroy` rather than `destory`.
> docs: fix simple typo, destory -> destroy

- src/ngx_http_vhost_traffic_status_display.c
> fix: limit the r->uri search scope to avoid overflow

- src/ngx_http_vhost_traffic_status_shm.c
Very small patch to cast the key length to the correct type for the `ngx_http_vhost_traffic_status_node_t`. Without this change, keys over 255 characters are not passed through correctly, and corrupt the output data.
> Cast key length to correct type

- src/ngx_http_vhost_traffic_status_node.c
- src/ngx_http_vhost_traffic_status_node.h
The `ngx_http_vhost_traffic_status_node_init` function initializes several data structures and then processes the first request. Subsequent requests are then processed by `ngx_http_vhost_traffic_status_node_set`. When histogram buckets were introduced, the `ngx_http_vhost_traffic_status_node_set` function was modified to increment the counters in the buckets. However `ngx_http_vhost_traffic_status_node_init` was not modified to increment the histogram buckets for the first request.
This PR refactors the common code from these functions into a common `ngx_http_vhost_traffic_status_node_update` function to fix this omission and to reduce the chance of similar problems.
> Set histogram buckets on first request

- src/ngx_http_vhost_traffic_status_display_prometheus.c
- src/ngx_http_vhost_traffic_status_string.c
- src/ngx_http_vhost_traffic_status_string.h
This PR updates and replaces https://github.com/vozlt/nginx-module-vts/pull/151 with the changes suggested in my review comments, such as escaping all special characters and fixing the incorrect size provided to the `ngx_utf8_decode` function.
In particular, the original code allocated a buffer 5 times the input string size. This code changes the code to initially scan for the first character that needs escaping. If no such character is found, it returns the original string, preventing the need for any memory allocation. If a character is found that needs escaping, this code allocates less memory for the unescaped prefix.
Although not much of it remains, the original PR was invaluable in getting this to work, so I have added @fshabir as a co-author.
> Escape special characters in Prometheus output

- src/ngx_http_vhost_traffic_status_display_prometheus.c
- src/ngx_http_vhost_traffic_status_display_prometheus.h
* Remove `code="total"` instances; this is better computed when needed by Prometheus itself
* Fix label naming
> Prometheus request count label fixes

- src/ngx_http_vhost_traffic_status_display_json.c
I believe the nginx_upstream_check_module is widely used for checking upstreams and we find this patch very useful for updating the upstream status  as soon as the healthcheck fails. It check the upstream status if the nginx_upstream_check_module module is enabled/defined.
> Add support for nginx_upstream_check_module module

- README.md
The description of the observe buckets in the vhost_traffic_status_histogram_buckets is incorrect.
> Docs: Fix README

- .github/workflows/ci.yml
- t/021.set_by_filter.t
SSAI.
This PR can be only confirm whether it can build the nginx with this modules via the github actions.
I've given up to make test stages because a several tests which concerned about upstream zone features obviously failedI've given up to make test stages because a several tests which concerned about upstream zone features obviously failed.
> Add github actions

- README.md
- src/ngx_http_vhost_traffic_status_module.h
After merging https://github.com/vozlt/nginx-module-vts/pull/240
I found a lack of changing module version...
@SuperQ 
If it does not  automate here, it should be change every time. What can you do that?
> chore: Change module version.

- .github/workflows/ci.yml
Fixes: https://github.com/vozlt/nginx-module-vts/issues/232
fixes ci without -Wno-stringop-overread
> test: build without -Wno-stringop-overread

- src/ngx_http_vhost_traffic_status_shm.c
`ngx_http_vhost_traffic_status_shm_add_node` does not unlock if it returns from line 133 nevertheless it acquires the lock at line 107.
https://github.com/vozlt/nginx-module-vts/blob/0009b3bc668a7d73751c4cd8f8c0a161cba96832/src/ngx_http_vhost_traffic_status_shm.c#L107-L133
> bugfix: Add shmtx unlock

- t/023.histogram_buckets.t
@vozlt @SuperQ 
Hi, happy new year! I wish it will be a good year for you all and this module :-)
vhost_traffic_status_histogram_buckets has no test at all, So I added the test.
> Add histogram_bucket test

- .github/workflows/ci.yml
- t/024.upstream_check.t
relivant: #227, #258, #262
Adding upstream status test with nginx_upstream_check_module.
> test: Add upstream check test

- src/ngx_http_vhost_traffic_status_string.c
* Fixes #142
* it can be escaped the 2 - 4 bytes character
in detail, please read below.
https://github.com/vozlt/nginx-module-vts/issues/142#issuecomment-1431427669
> Fix escaping filter_key in prometheus output

- src/ngx_http_vhost_traffic_status_dump.c
- src/ngx_http_vhost_traffic_status_node.h
- src/ngx_http_vhost_traffic_status_shm.c
Fixes #269 
The type of ngx_str_t.len is size_t. So it has occured the type mismatch between vtsn->len and key->len.
https://github.com/nginx/nginx/blob/dfe70f74a3558f05142fb552cea239add123d414/src/core/ngx_string.h#L17
OTOH, ngx_read_file returns the value which type is ssize_t, it should realize casting safty between ssize_t and size_t
in ngx_http_vhost_traffic_status_dump_restore.
FYI: https://stackoverflow.com/questions/16086331/cast-ssize-t-or-size-t
> Fix vtsn.len type #269

- .github/workflows/ci.yml
Early this year, we heard that main nginx upstream had divided into F5 support and open development one.
It should be better to support the CI to confirm our module build and test some feature works well both of them.
https://freenginx.org/en/
> ci: support freenginx

- README.md
Fixes #283 
Add an example of the build process explanation to make the Profile-Guided Optimization binary.
> Add example of build process for PGO supported binary #283

- src/ngx_http_vhost_traffic_status_display.c
- src/ngx_http_vhost_traffic_status_string.c
- t/007.control_status_group.t
- t/008.control_status_zone.t
Fixes: #279 
support encoding `@`, `:`, `*` for group and zone.
> Support query string encoding for control API #279

- README.md
- src/ngx_http_vhost_traffic_status_display_json.c
- src/ngx_http_vhost_traffic_status_display_prometheus.c
- src/ngx_http_vhost_traffic_status_module.c
- src/ngx_http_vhost_traffic_status_module.h
Add new boolean flag `vhost_traffic_status_stats_by_upstream` to allow disabling statistics collection for upstream servers.
fixes: #292
> Introduce vhost_traffic_status_stats_by_upstream

- .github/workflows/ci.yml
This PR will explicitly pin the CI runner image to Ubuntu 24.04 and use the already installed libpcre2-dev package instead of manually checking it out from source.
> Pin CI to Ubuntu 24.04, use system libpcre2-dev package

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
- .github/ISSUE_TEMPLATE/submit_question.yaml
Add issue template not only to be able to describe the feature or the bug report details without ambiguity for users but also to prevent to disgust or make difficulty to watching or triaging the issues.
> Add issue template
